spring.datasource.url=jdbc:postgresql://localhost:5432/corebank_db
spring.datasource.username=postgres
spring.datasource.password=1207
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8085